In [47]:
import gensim
from owlready2 import *
import polars as pl
import numpy as np

In [2]:
word2vec_embedding_file = "../embeddings/ontology.embeddings"
onto_file = "../data/efo_otar_slim.owl"

model = gensim.models.Word2Vec.load(word2vec_embedding_file)
onto = get_ontology(onto_file).load()
classes = list(onto.classes())
c = classes[0]

iri_v = model.wv.get_vector(c.iri)

In [12]:
all_classes_iri = [c.iri for c in classes]

print(f"Number of class iri: {len(all_classes_iri)}")

Number of class iri: 57096

In [9]:
# read disease OT file 

disease_df = pl.read_parquet("../data/disease/disease.parquet")
disease_df.head(1)

shape: (1, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ code      ┆ name      ┆ descripti ┆ … ┆ therapeut ┆ descendan ┆ ontology  ┆ synonyms │
│ ---       ┆ ---       ┆ ---       ┆ on        ┆   ┆ icAreas   ┆ ts        ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ struct[3] ┆ struct[4 │
│           ┆           ┆           ┆ str       ┆   ┆ list[str] ┆ list[str] ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DOID_0050 ┆ http://pu ┆ synuclein ┆ A neurode ┆ … ┆ ["EFO_000 ┆ ["EFO_000 ┆ {false,fa ┆ {["alpha │
│ 890       ┆ rl.obolib ┆ opathy    ┆ generativ ┆   ┆ 0618",    ┆ 6792",    ┆ lse,{"htt ┆ Synuclei │
│           ┆ rary.org/ ┆           ┆ e disease ┆   ┆ "OTAR_000 ┆ "EFO_1001 ┆ p://purl. ┆ nopathie │
│           ┆ obo…      ┆           ┆ th…       ┆   ┆ 0020"…    ┆ 050",…    ┆ obo…      ┆ s", "…   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
disease_iri_codes = disease_df['code'].to_list()

# are all OT disease codes in EFO_slim iri? --> YES

print(f"N. of OT diseases: {len(set(disease_iri_codes))}")
print(f"N. of intersection: {len(set(disease_iri_codes) & set(all_classes_iri))}")

N. of OT diseases: 47030
N. of intersection: 47030

In [83]:

def get_embedding(iri):
    return model.wv.get_vector(iri).astype(np.float32).tolist()

embeddings = pl.DataFrame({'iri': disease_iri_codes}).with_columns(
    pl.col("iri")
    .map_elements(
        get_embedding,
        return_dtype=pl.List(pl.Float32)
    )
    .alias("embeddings")
)

In [84]:
embeddings.head(2)

shape: (2, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ iri                             ┆ embeddings                      │
│ ---                             ┆ ---                             │
│ str                             ┆ list[f32]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ http://purl.obolibrary.org/obo… ┆ [0.000494, -0.159378, … 0.1794… │
│ http://purl.obolibrary.org/obo… ┆ [0.047898, -0.144157, … 0.1983… │
└─────────────────────────────────┴─────────────────────────────────┘

In [85]:
embeddings.write_parquet("../output/embeddings.parquet", compression="brotli")

In [82]:
embeddings.height

57096